"use strict";

let app = require("../app");

app.directive("noTransclude", ()=>{
    return {
        restrict: 'E',
        scope: {

        },
        template: '<div> This is the text generated by a directive</div>'
    };
}).directive("usingTransclude", ()=>{
    return {
        restrict: 'E',
        transclude: true,
        scope: {

        },
        template: '<div> This is the text generated by a directive <br><span ng-transclude></span></div>'
    };
});